micronaut:
  application:
    name: security-server
  server:
    port: ${SEG360_SERVER_PORT:8080}
    thread-selection: AUTO
    cors:
      enabled: true
  http:
    services:
      apimercadolibre:
        urls:
          - "${API_ITEMS_URL:`https://api.mercadolibre.com/`}"

endpoints:
  health:
    enabled: False
    sensitive: False

datasources:
  default:
    url: ${SEG360_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/seg360`}
    username: ${SEG360_JDBC_USER:seg360}
    password: ${SEG360_JDBC_PASSWORD:Sec*969676}
    driverClassName: ${SEG360_JDBC_DRIVER:org.postgresql.Driver}

jpa:
  default:
    packages-to-scan:
      - 'security.server.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false

