micronaut:
  application:
    name: security-server
  server:
    port: ${SECURITY_SERVER_PORT:8080}
    thread-selection: AUTO
    cors:
      enabled: true
  http:
    services:
      apimercadolibre:
        urls:
          - "${API_ITEMS_URL:`https://api.mercadolibre.com/`}"

datasources:
  default:
    url: ${SECURITY_JDBC_URL:`jdbc:postgresql://localhost:5432/seg360`}
    username: ${SECURITY_JDBC_USER:seg360}
    password: ${SECURITY_JDBC_PASSWORD:Sec*969676}
    driverClassName: ${SECURITY_JDBC_DRIVER:org.postgresql.Driver}

jpa:
  default:
    packages-to-scan:
      - 'security.server.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false

